# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-


def build(bld):
    obj = bld.create_ns3_program('simple-network-example', ['lorawan'])
    obj.source = 'simple-network-example.cc'

    obj = bld.create_ns3_program('network-server-example', ['lorawan'])
    obj.source = 'network-server-example.cc'

    obj = bld.create_ns3_program('complete-network-example', ['lorawan'])
    obj.source = 'complete-network-example.cc'

    obj = bld.create_ns3_program('adr-example', ['lorawan'])
    obj.source = 'adr-example.cc'

    obj = bld.create_ns3_program('energy-model-example', ['lorawan'])
    obj.source = 'energy-model-example.cc'

    obj = bld.create_ns3_program('aloha-throughput', ['lorawan'])
    obj.source = 'aloha-throughput.cc'

    obj = bld.create_ns3_program('parallel-reception-example', ['lorawan'])
    obj.source = 'parallel-reception-example.cc'
    
    obj = bld.create_ns3_program('vemac-example', ['lorawan'])
    obj.source = 'vemac-example.cc'
    
    obj = bld.create_ns3_program('vemac-circle', ['lorawan'])
    obj.source = 'vemac-circle.cc'
    
    obj = bld.create_ns3_program('vemac-circle-accident', ['lorawan'])
    obj.source = 'vemac-circle-accident.cc'
    
    obj = bld.create_ns3_program('vemac-circle-accident_2', ['lorawan'])
    obj.source = 'vemac-circle-accident_2.cc'
    
    obj = bld.create_ns3_program('vemac-circle-hidden', ['lorawan'])
    obj.source = 'vemac-circle-hidden.cc'
